version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kuosc
      MONGO_INITDB_ROOT_PASSWORD: kuosc

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rishad
      ME_CONFIG_MONGODB_ADMINPASSWORD: rishad
      ME_CONFIG_MONGODB_URL: mongodb://kuosc:kuosc@mongodb:27017/
